version: '3.2'
networks: 
  default:
      external:
         name: ukc_default
services:
  ukc-client:
    container_name: ukc-client-encfs
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      # Common settings
      - UB_PARTITION=encfs
      - UB_KEY_NAME=encfs
      - UB_USER=user
      - UB_PASSWORD_FILE=/encfs_pass.txt

      # REST API settings
      - UB_CORE_URL=https://ukc-ep
      - UB_USER_PASSWORD=

      # CORE Client settings
      - UB_SERVER_NAME=ukc-ep
      - UB_CLIENT_TEMPLATE_NAME=
      - UB_CLIENT_ACTIVATION_CODE=

      # Demo settings
      - ENCFS_ROOT_DIR=~/.encfs_root
      - ENCFS_MOUNT_POINT=~/encfs_mount