version: '3.2'
networks: 
  default:
      external:
         name: ukc_default
services:
  ukc-client:
    container_name: ukc-client-encfs
    privileged: true
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      # These argumets are used for both REST API and Client
      # - UB_PARTITION=encfs
      # - UB_USER_PASSWORD=Unbound1!
      # The default user password is empty, you can set it if you change
      # - UB_USER=user
      - UB_USER=adam2
      - UB_USER_PASSWORD=Unbound1!
      - UB_KEY_NAME=encfs
      - UB_PASSWORD_FILE=/encfs_pass.txt
      
      # This argument is required only for REST API
      - UB_CORE_URL=https://ukc-ep
      
      # Uncoment and set these argumets if your'e using
      # Core Client software
      - UB_SERVER_NAME=ukc-ep
      - UB_CLIENT_TEMPLATE_NAME=tmp1
      - UB_CLIENT_ACTIVATION_CODE=8614832401071093

      - ENCFS_ROOT_DIR=/.encfs_root
      - ENCFS_MOUNT_POINT=/encfs_mount
      
    volumes:
      - ./data:/data
      - ../bash-scripts:/bash-scripts
    