#!/bin/bash

# Get a strong password encrypted by an RSA key stored in Unbound CORE
# Encrypt with Unbound CORE Client if installed
# Othewise, use Unbound CORE REST API which can be a bit less secure
if [[ $UNBOUND_CLIENT_INSTALLLED -eq 1 ]]; then 
    tmp_passphrase=$(ub-get-password-with-core-client)
else
    tmp_passphrase=$(ub-get-password-with-rest-api)
fi
echo $tmp_passphrase